/**
 * Справочник стран для поля телефона: код, русское название, маска ввода и
 * допустимые длины национального номера.
 *
 * Источник данных — открытый набор countries-phone-masks (MIT), приведён к
 * нашему виду: русские названия, длины выведены из масок, страны СНГ подняты
 * наверх списка. Файл сгенерирован, править руками не нужно — при обновлении
 * пересобрать из исходного набора.
 *
 * Казахстану проставлен код +7 (в исходнике +77): «7» после кода — это часть
 * номера, а не отдельный код страны, иначе номер получался на цифру длиннее.
 */

export interface PhoneCountry {
  /** ISO 3166-1 alpha-2, он же имя файла флага. */
  iso: string;
  /** Международный код с плюсом: «+7», «+994». */
  dial: string;
  /** Название по-русски — то, что видит партнёр. */
  name: string;
  /** Английское название — для поиска по списку латиницей. */
  nameEn: string;
  /** Маска ввода национальной части: «#» — цифра. */
  mask: string;
  /** Допустимые длины национальной части (без кода страны). */
  lengths: number[];
}

export const PHONE_COUNTRIES: PhoneCountry[] = [
  {
    iso: "RU",
    dial: "+7",
    name: "Россия",
    nameEn: "Russia",
    mask: "(###) ###-##-##",
    lengths: [10],
  },
  {
    iso: "KZ",
    dial: "+7",
    name: "Казахстан",
    nameEn: "Kazakhstan",
    mask: "(###) ### ## ##",
    lengths: [10],
  },
  {
    iso: "AZ",
    dial: "+994",
    name: "Азербайджан",
    nameEn: "Azerbaijan",
    mask: "##-###-##-##",
    lengths: [9],
  },
  {
    iso: "GE",
    dial: "+995",
    name: "Грузия",
    nameEn: "Georgia",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "AM",
    dial: "+374",
    name: "Армения",
    nameEn: "Armenia",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "BY",
    dial: "+375",
    name: "Беларусь",
    nameEn: "Belarus",
    mask: "(##) ###-##-##",
    lengths: [9],
  },
  {
    iso: "UA",
    dial: "+380",
    name: "Украина",
    nameEn: "Ukraine",
    mask: "(##) ###-##-##",
    lengths: [9],
  },
  {
    iso: "UZ",
    dial: "+998",
    name: "Узбекистан",
    nameEn: "Uzbekistan",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "TJ",
    dial: "+992",
    name: "Таджикистан",
    nameEn: "Tajikistan",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "KG",
    dial: "+996",
    name: "Киргизия",
    nameEn: "Kyrgyzstan",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "TM",
    dial: "+993",
    name: "Туркменистан",
    nameEn: "Turkmenistan",
    mask: "#-###-####",
    lengths: [8],
  },
  {
    iso: "MD",
    dial: "+373",
    name: "Молдова",
    nameEn: "Moldova",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "TR",
    dial: "+90",
    name: "Турция",
    nameEn: "Turkey",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "AE",
    dial: "+971",
    name: "ОАЭ",
    nameEn: "United Arab Emirates",
    mask: "#-###-####",
    lengths: [8],
  },
  {
    iso: "AU",
    dial: "+61",
    name: "Австралия",
    nameEn: "Australia",
    mask: "#-####-####",
    lengths: [9],
  },
  {
    iso: "AT",
    dial: "+43",
    name: "Австрия",
    nameEn: "Austria",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "AX",
    dial: "+358",
    name: "Аландские о-ва",
    nameEn: "Aland Islands",
    mask: "(###) ###-##-##",
    lengths: [10],
  },
  {
    iso: "AL",
    dial: "+355",
    name: "Албания",
    nameEn: "Albania",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "DZ",
    dial: "+213",
    name: "Алжир",
    nameEn: "Algeria",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "AS",
    dial: "+1",
    name: "Американское Самоа",
    nameEn: "American Samoa",
    mask: "(684) ###-####",
    lengths: [7],
  },
  {
    iso: "AI",
    dial: "+1",
    name: "Ангилья",
    nameEn: "Anguilla",
    mask: "(264) ###-####",
    lengths: [7],
  },
  {
    iso: "AO",
    dial: "+244",
    name: "Ангола",
    nameEn: "Angola",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "AD",
    dial: "+376",
    name: "Андорра",
    nameEn: "Andorra",
    mask: "###-###",
    lengths: [6],
  },
  {
    iso: "AQ",
    dial: "+672",
    name: "Антарктида",
    nameEn: "Antarctica",
    mask: "1##-###",
    lengths: [5],
  },
  {
    iso: "AG",
    dial: "+1",
    name: "Антигуа и Барбуда",
    nameEn: "Antigua and Barbuda",
    mask: "(268) ###-####",
    lengths: [7],
  },
  {
    iso: "AR",
    dial: "+54",
    name: "Аргентина",
    nameEn: "Argentina",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "AW",
    dial: "+297",
    name: "Аруба",
    nameEn: "Aruba",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "AF",
    dial: "+93",
    name: "Афганистан",
    nameEn: "Afghanistan",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "BS",
    dial: "+1",
    name: "Багамы",
    nameEn: "Bahamas",
    mask: "(242) ###-####",
    lengths: [7],
  },
  {
    iso: "BD",
    dial: "+880",
    name: "Бангладеш",
    nameEn: "Bangladesh",
    mask: "1###-######",
    lengths: [9],
  },
  {
    iso: "BB",
    dial: "+1",
    name: "Барбадос",
    nameEn: "Barbados",
    mask: "(246) ###-####",
    lengths: [7],
  },
  {
    iso: "BH",
    dial: "+973",
    name: "Бахрейн",
    nameEn: "Bahrain",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "BZ",
    dial: "+501",
    name: "Белиз",
    nameEn: "Belize",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "BE",
    dial: "+32",
    name: "Бельгия",
    nameEn: "Belgium",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "BJ",
    dial: "+229",
    name: "Бенин",
    nameEn: "Benin",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "BM",
    dial: "+1",
    name: "Бермудские о-ва",
    nameEn: "Bermuda",
    mask: "(441) ###-####",
    lengths: [7],
  },
  {
    iso: "BG",
    dial: "+359",
    name: "Болгария",
    nameEn: "Bulgaria",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "BO",
    dial: "+591",
    name: "Боливия",
    nameEn: "Bolivia",
    mask: "#-###-####",
    lengths: [8],
  },
  {
    iso: "BA",
    dial: "+387",
    name: "Босния и Герцеговина",
    nameEn: "Bosnia and Herzegovina",
    mask: "##-####",
    lengths: [6, 7],
  },
  {
    iso: "BW",
    dial: "+267",
    name: "Ботсвана",
    nameEn: "Botswana",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "BR",
    dial: "+55",
    name: "Бразилия",
    nameEn: "Brazil",
    mask: "(##) ####-####",
    lengths: [10, 11],
  },
  {
    iso: "IO",
    dial: "+246",
    name: "Британская территория в Индийском океане",
    nameEn: "British Indian Ocean Territory",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "BN",
    dial: "+673",
    name: "Бруней",
    nameEn: "Brunei Darussalam",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "BF",
    dial: "+226",
    name: "Буркина-Фасо",
    nameEn: "Burkina Faso",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "BI",
    dial: "+257",
    name: "Бурунди",
    nameEn: "Burundi",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "BT",
    dial: "+975",
    name: "Бутан",
    nameEn: "Bhutan",
    mask: "17-###-###",
    lengths: [6, 7],
  },
  {
    iso: "VU",
    dial: "+678",
    name: "Вануату",
    nameEn: "Vanuatu",
    mask: "#####",
    lengths: [5, 7],
  },
  {
    iso: "VA",
    dial: "+39",
    name: "Ватикан",
    nameEn: "Holy See (Vatican City State)",
    mask: "06 698#####",
    lengths: [5],
  },
  {
    iso: "GB",
    dial: "+44",
    name: "Великобритания",
    nameEn: "United Kingdom",
    mask: "##-####-####",
    lengths: [10],
  },
  {
    iso: "HU",
    dial: "+36",
    name: "Венгрия",
    nameEn: "Hungary",
    mask: "## ### ####",
    lengths: [9],
  },
  {
    iso: "VE",
    dial: "+58",
    name: "Венесуэла",
    nameEn: "Venezuela, Bolivarian Republic of Venezuela",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "VG",
    dial: "+1",
    name: "Виргинские о-ва (Великобритания)",
    nameEn: "Virgin Islands, British",
    mask: "(284) ###-####",
    lengths: [7],
  },
  {
    iso: "VI",
    dial: "+1",
    name: "Виргинские о-ва (США)",
    nameEn: "Virgin Islands, U.S.",
    mask: "(340) ###-####",
    lengths: [7],
  },
  {
    iso: "TL",
    dial: "+670",
    name: "Восточный Тимор",
    nameEn: "Timor-Leste",
    mask: "77#-#####",
    lengths: [6, 7],
  },
  {
    iso: "VN",
    dial: "+84",
    name: "Вьетнам",
    nameEn: "Vietnam",
    mask: "##-####-###",
    lengths: [9, 10],
  },
  {
    iso: "GA",
    dial: "+241",
    name: "Габон",
    nameEn: "Gabon",
    mask: "# ## ## ##",
    lengths: [7],
  },
  {
    iso: "HT",
    dial: "+509",
    name: "Гаити",
    nameEn: "Haiti",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "GY",
    dial: "+592",
    name: "Гайана",
    nameEn: "Guyana",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "GM",
    dial: "+220",
    name: "Гамбия",
    nameEn: "Gambia",
    mask: "### ####",
    lengths: [7],
  },
  {
    iso: "GH",
    dial: "+233",
    name: "Гана",
    nameEn: "Ghana",
    mask: "03# ### ####",
    lengths: [8],
  },
  {
    iso: "GP",
    dial: "+590",
    name: "Гваделупа",
    nameEn: "Guadeloupe",
    mask: "### ## ## ##",
    lengths: [9],
  },
  {
    iso: "GT",
    dial: "+502",
    name: "Гватемала",
    nameEn: "Guatemala",
    mask: "#-###-####",
    lengths: [8],
  },
  {
    iso: "GN",
    dial: "+224",
    name: "Гвинея",
    nameEn: "Guinea",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "GW",
    dial: "+245",
    name: "Гвинея-Бисау",
    nameEn: "Guinea-Bissau",
    mask: "#-######",
    lengths: [7],
  },
  {
    iso: "DE",
    dial: "+49",
    name: "Германия",
    nameEn: "Germany",
    mask: "###-###",
    lengths: [6, 10, 11],
  },
  {
    iso: "GG",
    dial: "+44",
    name: "Гернси",
    nameEn: "Guernsey",
    mask: "(####) ######",
    lengths: [10],
  },
  {
    iso: "GI",
    dial: "+350",
    name: "Гибралтар",
    nameEn: "Gibraltar",
    mask: "###-#####",
    lengths: [8],
  },
  {
    iso: "HN",
    dial: "+504",
    name: "Гондурас",
    nameEn: "Honduras",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "HK",
    dial: "+852",
    name: "Гонконг (САР)",
    nameEn: "Hong Kong",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "GD",
    dial: "+1",
    name: "Гренада",
    nameEn: "Grenada",
    mask: "(473) ###-####",
    lengths: [7],
  },
  {
    iso: "GL",
    dial: "+299",
    name: "Гренландия",
    nameEn: "Greenland",
    mask: "##-##-##",
    lengths: [6],
  },
  {
    iso: "GR",
    dial: "+30",
    name: "Греция",
    nameEn: "Greece",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "GU",
    dial: "+1",
    name: "Гуам",
    nameEn: "Guam",
    mask: "671 ### ####",
    lengths: [7],
  },
  {
    iso: "DK",
    dial: "+45",
    name: "Дания",
    nameEn: "Denmark",
    mask: "##-##-##-##",
    lengths: [8],
  },
  {
    iso: "JE",
    dial: "+44",
    name: "Джерси",
    nameEn: "Jersey",
    mask: "(####) ####-######",
    lengths: [14],
  },
  {
    iso: "DJ",
    dial: "+253",
    name: "Джибути",
    nameEn: "Djibouti",
    mask: "##-##-##-##",
    lengths: [8],
  },
  {
    iso: "DM",
    dial: "+1",
    name: "Доминика",
    nameEn: "Dominica",
    mask: "(767) ###-####",
    lengths: [7],
  },
  {
    iso: "DO",
    dial: "+1",
    name: "Доминиканская Республика",
    nameEn: "Dominican Republic",
    mask: "(809) ###-####",
    lengths: [7],
  },
  {
    iso: "EG",
    dial: "+20",
    name: "Египет",
    nameEn: "Egypt",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "ZM",
    dial: "+260",
    name: "Замбия",
    nameEn: "Zambia",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "ZW",
    dial: "+263",
    name: "Зимбабве",
    nameEn: "Zimbabwe",
    mask: "#-######",
    lengths: [7],
  },
  {
    iso: "IL",
    dial: "+972",
    name: "Израиль",
    nameEn: "Israel",
    mask: "#-###-####",
    lengths: [8],
  },
  {
    iso: "IN",
    dial: "+91",
    name: "Индия",
    nameEn: "India",
    mask: "(####) ###-###",
    lengths: [10],
  },
  {
    iso: "ID",
    dial: "+62",
    name: "Индонезия",
    nameEn: "Indonesia",
    mask: "##-###-##",
    lengths: [7, 8, 9, 10],
  },
  {
    iso: "JO",
    dial: "+962",
    name: "Иордания",
    nameEn: "Jordan",
    mask: "#-####-####",
    lengths: [9],
  },
  {
    iso: "IQ",
    dial: "+964",
    name: "Ирак",
    nameEn: "Iraq",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "IR",
    dial: "+98",
    name: "Иран",
    nameEn: "Iran",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "IE",
    dial: "+353",
    name: "Ирландия",
    nameEn: "Ireland",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "IS",
    dial: "+354",
    name: "Исландия",
    nameEn: "Iceland",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "ES",
    dial: "+34",
    name: "Испания",
    nameEn: "Spain",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "IT",
    dial: "+39",
    name: "Италия",
    nameEn: "Italy",
    mask: "(###) ####-###",
    lengths: [10],
  },
  {
    iso: "YE",
    dial: "+967",
    name: "Йемен",
    nameEn: "Yemen",
    mask: "#-###-###",
    lengths: [7, 8, 9],
  },
  {
    iso: "CV",
    dial: "+238",
    name: "Кабо-Верде",
    nameEn: "Cape Verde",
    mask: "(###) ##-##",
    lengths: [7],
  },
  {
    iso: "KH",
    dial: "+855",
    name: "Камбоджа",
    nameEn: "Cambodia",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "CM",
    dial: "+237",
    name: "Камерун",
    nameEn: "Cameroon",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "CA",
    dial: "+1",
    name: "Канада",
    nameEn: "Canada",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "QA",
    dial: "+974",
    name: "Катар",
    nameEn: "Qatar",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "KE",
    dial: "+254",
    name: "Кения",
    nameEn: "Kenya",
    mask: "###-######",
    lengths: [9],
  },
  {
    iso: "CY",
    dial: "+357",
    name: "Кипр",
    nameEn: "Cyprus",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "KI",
    dial: "+686",
    name: "Кирибати",
    nameEn: "Kiribati",
    mask: "##-###",
    lengths: [5],
  },
  {
    iso: "CN",
    dial: "+86",
    name: "Китай",
    nameEn: "China",
    mask: "(###) ####-###",
    lengths: [10, 11, 12],
  },
  {
    iso: "KP",
    dial: "+850",
    name: "КНДР",
    nameEn: "Korea, Democratic People's Republic of Korea",
    mask: "###-###",
    lengths: [6, 7, 8, 10, 17],
  },
  {
    iso: "CC",
    dial: "+61",
    name: "Кокосовые о-ва",
    nameEn: "Cocos (Keeling) Islands",
    mask: "#-####-####",
    lengths: [9],
  },
  {
    iso: "CO",
    dial: "+57",
    name: "Колумбия",
    nameEn: "Colombia",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "KM",
    dial: "+269",
    name: "Коморы",
    nameEn: "Comoros",
    mask: "##-#####",
    lengths: [7],
  },
  {
    iso: "CG",
    dial: "+242",
    name: "Конго - Браззавиль",
    nameEn: "Congo",
    mask: "##-#####",
    lengths: [7],
  },
  {
    iso: "CD",
    dial: "+243",
    name: "Конго - Киншаса",
    nameEn: "Democratic Republic of the Congo",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "XK",
    dial: "+383",
    name: "Косово",
    nameEn: "Kosovo",
    mask: "##-###-###",
    lengths: [8, 9],
  },
  {
    iso: "CR",
    dial: "+506",
    name: "Коста-Рика",
    nameEn: "Costa Rica",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "CI",
    dial: "+225",
    name: "Кот-д’Ивуар",
    nameEn: "Ivory Coast / Cote d'Ivoire",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "CU",
    dial: "+53",
    name: "Куба",
    nameEn: "Cuba",
    mask: "#-###-####",
    lengths: [8],
  },
  {
    iso: "KW",
    dial: "+965",
    name: "Кувейт",
    nameEn: "Kuwait",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "LA",
    dial: "+856",
    name: "Лаос",
    nameEn: "Laos",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "LV",
    dial: "+371",
    name: "Латвия",
    nameEn: "Latvia",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "LS",
    dial: "+266",
    name: "Лесото",
    nameEn: "Lesotho",
    mask: "#-###-####",
    lengths: [8],
  },
  {
    iso: "LR",
    dial: "+231",
    name: "Либерия",
    nameEn: "Liberia",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "LB",
    dial: "+961",
    name: "Ливан",
    nameEn: "Lebanon",
    mask: "#-###-###",
    lengths: [7, 8],
  },
  {
    iso: "LY",
    dial: "+218",
    name: "Ливия",
    nameEn: "Libya",
    mask: "21-###-####",
    lengths: [7, 8],
  },
  {
    iso: "LT",
    dial: "+370",
    name: "Литва",
    nameEn: "Lithuania",
    mask: "(###) ##-###",
    lengths: [8],
  },
  {
    iso: "LI",
    dial: "+423",
    name: "Лихтенштейн",
    nameEn: "Liechtenstein",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "LU",
    dial: "+352",
    name: "Люксембург",
    nameEn: "Luxembourg",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "MU",
    dial: "+230",
    name: "Маврикий",
    nameEn: "Mauritius",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "MR",
    dial: "+222",
    name: "Мавритания",
    nameEn: "Mauritania",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "MG",
    dial: "+261",
    name: "Мадагаскар",
    nameEn: "Madagascar",
    mask: "##-##-#####",
    lengths: [9],
  },
  {
    iso: "YT",
    dial: "+262",
    name: "Майотта",
    nameEn: "Mayotte",
    mask: "#####-####",
    lengths: [9],
  },
  {
    iso: "MO",
    dial: "+853",
    name: "Макао (САР)",
    nameEn: "Macau",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "MW",
    dial: "+265",
    name: "Малави",
    nameEn: "Malawi",
    mask: "1-###-###",
    lengths: [6, 9],
  },
  {
    iso: "MY",
    dial: "+60",
    name: "Малайзия",
    nameEn: "Malaysia",
    mask: "#-###-###",
    lengths: [7, 8, 9],
  },
  {
    iso: "ML",
    dial: "+223",
    name: "Мали",
    nameEn: "Mali",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "MV",
    dial: "+960",
    name: "Мальдивы",
    nameEn: "Maldives",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "MT",
    dial: "+356",
    name: "Мальта",
    nameEn: "Malta",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "MA",
    dial: "+212",
    name: "Марокко",
    nameEn: "Morocco",
    mask: "##-####-###",
    lengths: [9],
  },
  {
    iso: "MQ",
    dial: "+596",
    name: "Мартиника",
    nameEn: "Martinique",
    mask: "(###) ##-##-##",
    lengths: [9],
  },
  {
    iso: "MH",
    dial: "+692",
    name: "Маршалловы о-ва",
    nameEn: "Marshall Islands",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "MX",
    dial: "+52",
    name: "Мексика",
    nameEn: "Mexico",
    mask: "##-##-####",
    lengths: [8, 10],
  },
  {
    iso: "MZ",
    dial: "+258",
    name: "Мозамбик",
    nameEn: "Mozambique",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "MC",
    dial: "+377",
    name: "Монако",
    nameEn: "Monaco",
    mask: "##-###-###",
    lengths: [8, 9],
  },
  {
    iso: "MN",
    dial: "+976",
    name: "Монголия",
    nameEn: "Mongolia",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "MS",
    dial: "+1",
    name: "Монтсеррат",
    nameEn: "Montserrat",
    mask: "(664) ###-####",
    lengths: [7],
  },
  {
    iso: "MM",
    dial: "+95",
    name: "Мьянма (Бирма)",
    nameEn: "Myanmar",
    mask: "###-###",
    lengths: [6, 7, 8],
  },
  {
    iso: "NA",
    dial: "+264",
    name: "Намибия",
    nameEn: "Namibia",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "NR",
    dial: "+674",
    name: "Науру",
    nameEn: "Nauru",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "NP",
    dial: "+977",
    name: "Непал",
    nameEn: "Nepal",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "NE",
    dial: "+227",
    name: "Нигер",
    nameEn: "Niger",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "NG",
    dial: "+234",
    name: "Нигерия",
    nameEn: "Nigeria",
    mask: "##-###-##",
    lengths: [7, 8, 10],
  },
  {
    iso: "NL",
    dial: "+31",
    name: "Нидерланды",
    nameEn: "Netherlands",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "NI",
    dial: "+505",
    name: "Никарагуа",
    nameEn: "Nicaragua",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "NU",
    dial: "+683",
    name: "Ниуэ",
    nameEn: "Niue",
    mask: "####",
    lengths: [4],
  },
  {
    iso: "NZ",
    dial: "+64",
    name: "Новая Зеландия",
    nameEn: "New Zealand",
    mask: "#-###-###",
    lengths: [7, 9, 10],
  },
  {
    iso: "NC",
    dial: "+687",
    name: "Новая Каледония",
    nameEn: "New Caledonia",
    mask: "##-####",
    lengths: [6],
  },
  {
    iso: "NO",
    dial: "+47",
    name: "Норвегия",
    nameEn: "Norway",
    mask: "(###) ##-###",
    lengths: [8],
  },
  {
    iso: "AC",
    dial: "+247",
    name: "о-в Вознесения",
    nameEn: "Ascension Island",
    mask: "####",
    lengths: [4],
  },
  {
    iso: "IM",
    dial: "+44",
    name: "о-в Мэн",
    nameEn: "Isle of Man",
    mask: "(####) ######",
    lengths: [10],
  },
  {
    iso: "NF",
    dial: "+672",
    name: "о-в Норфолк",
    nameEn: "Norfolk Island",
    mask: "3##-###",
    lengths: [5],
  },
  {
    iso: "CX",
    dial: "+61",
    name: "о-в Рождества",
    nameEn: "Christmas Island",
    mask: "#-####-####",
    lengths: [9],
  },
  {
    iso: "SH",
    dial: "+290",
    name: "о-в Св. Елены",
    nameEn: "Saint Helena, Ascension and Tristan Da Cunha",
    mask: "####",
    lengths: [4],
  },
  {
    iso: "KY",
    dial: "+1",
    name: "о-ва Кайман",
    nameEn: "Cayman Islands",
    mask: "(345) ###-####",
    lengths: [7],
  },
  {
    iso: "CK",
    dial: "+682",
    name: "о-ва Кука",
    nameEn: "Cook Islands",
    mask: "##-###",
    lengths: [5],
  },
  {
    iso: "PN",
    dial: "+870",
    name: "о-ва Питкэрн",
    nameEn: "Pitcairn",
    mask: "###-###-###",
    lengths: [9],
  },
  {
    iso: "OM",
    dial: "+968",
    name: "Оман",
    nameEn: "Oman",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "PK",
    dial: "+92",
    name: "Пакистан",
    nameEn: "Pakistan",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "PW",
    dial: "+680",
    name: "Палау",
    nameEn: "Palau",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "PS",
    dial: "+970",
    name: "Палестинские территории",
    nameEn: "Palestine",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "PA",
    dial: "+507",
    name: "Панама",
    nameEn: "Panama",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "PG",
    dial: "+675",
    name: "Папуа — Новая Гвинея",
    nameEn: "Papua New Guinea",
    mask: "(###) ##-###",
    lengths: [8],
  },
  {
    iso: "PY",
    dial: "+595",
    name: "Парагвай",
    nameEn: "Paraguay",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "PE",
    dial: "+51",
    name: "Перу",
    nameEn: "Peru",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "PL",
    dial: "+48",
    name: "Польша",
    nameEn: "Poland",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "PT",
    dial: "+351",
    name: "Португалия",
    nameEn: "Portugal",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "PR",
    dial: "+1",
    name: "Пуэрто-Рико",
    nameEn: "Puerto Rico",
    mask: "(787) ### ####",
    lengths: [7],
  },
  {
    iso: "KR",
    dial: "+82",
    name: "Республика Корея",
    nameEn: "Korea, Republic of South Korea",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "RE",
    dial: "+262",
    name: "Реюньон",
    nameEn: "Reunion",
    mask: "#####-####",
    lengths: [9],
  },
  {
    iso: "RW",
    dial: "+250",
    name: "Руанда",
    nameEn: "Rwanda",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "RO",
    dial: "+40",
    name: "Румыния",
    nameEn: "Romania",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "SV",
    dial: "+503",
    name: "Сальвадор",
    nameEn: "El Salvador",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "WS",
    dial: "+685",
    name: "Самоа",
    nameEn: "Samoa",
    mask: "##-####",
    lengths: [6],
  },
  {
    iso: "SM",
    dial: "+378",
    name: "Сан-Марино",
    nameEn: "San Marino",
    mask: "####-######",
    lengths: [10],
  },
  {
    iso: "ST",
    dial: "+239",
    name: "Сан-Томе и Принсипи",
    nameEn: "Sao Tome and Principe",
    mask: "##-#####",
    lengths: [7],
  },
  {
    iso: "SA",
    dial: "+966",
    name: "Саудовская Аравия",
    nameEn: "Saudi Arabia",
    mask: "#-###-####",
    lengths: [8, 9],
  },
  {
    iso: "MK",
    dial: "+389",
    name: "Северная Македония",
    nameEn: "North Macedonia",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "MP",
    dial: "+1",
    name: "Северные Марианские о-ва",
    nameEn: "Northern Mariana Islands",
    mask: "(670) ###-####",
    lengths: [7],
  },
  {
    iso: "SC",
    dial: "+248",
    name: "Сейшельские о-ва",
    nameEn: "Seychelles",
    mask: "#-###-###",
    lengths: [7],
  },
  {
    iso: "BL",
    dial: "+590",
    name: "Сен-Бартелеми",
    nameEn: "Saint Barthelemy",
    mask: "###-##-##-##",
    lengths: [9],
  },
  {
    iso: "MF",
    dial: "+590",
    name: "Сен-Мартен",
    nameEn: "Saint Martin",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "PM",
    dial: "+508",
    name: "Сен-Пьер и Микелон",
    nameEn: "Saint Pierre and Miquelon",
    mask: "##-####",
    lengths: [6],
  },
  {
    iso: "SN",
    dial: "+221",
    name: "Сенегал",
    nameEn: "Senegal",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "VC",
    dial: "+1",
    name: "Сент-Винсент и Гренадины",
    nameEn: "Saint Vincent and the Grenadines",
    mask: "(784) ###-####",
    lengths: [7],
  },
  {
    iso: "KN",
    dial: "+1",
    name: "Сент-Китс и Невис",
    nameEn: "Saint Kitts and Nevis",
    mask: "(869) ###-####",
    lengths: [7],
  },
  {
    iso: "LC",
    dial: "+1",
    name: "Сент-Люсия",
    nameEn: "Saint Lucia",
    mask: "(758) ###-####",
    lengths: [7],
  },
  {
    iso: "RS",
    dial: "+381",
    name: "Сербия",
    nameEn: "Serbia",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "SG",
    dial: "+65",
    name: "Сингапур",
    nameEn: "Singapore",
    mask: "####-####",
    lengths: [8],
  },
  {
    iso: "SX",
    dial: "+1",
    name: "Синт-Мартен",
    nameEn: "Sint Maarten",
    mask: "(721) ###-####",
    lengths: [7],
  },
  {
    iso: "SY",
    dial: "+963",
    name: "Сирия",
    nameEn: "Syrian Arab Republic",
    mask: "##-####-###",
    lengths: [9],
  },
  {
    iso: "SK",
    dial: "+421",
    name: "Словакия",
    nameEn: "Slovakia",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "SI",
    dial: "+386",
    name: "Словения",
    nameEn: "Slovenia",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "US",
    dial: "+1",
    name: "Соединенные Штаты",
    nameEn: "United States",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "SB",
    dial: "+677",
    name: "Соломоновы о-ва",
    nameEn: "Solomon Islands",
    mask: "#####",
    lengths: [5, 7],
  },
  {
    iso: "SO",
    dial: "+252",
    name: "Сомали",
    nameEn: "Somalia",
    mask: "#-###-###",
    lengths: [7, 8],
  },
  {
    iso: "SD",
    dial: "+249",
    name: "Судан",
    nameEn: "Sudan",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "SR",
    dial: "+597",
    name: "Суринам",
    nameEn: "Suriname",
    mask: "###-###",
    lengths: [6, 7],
  },
  {
    iso: "SL",
    dial: "+232",
    name: "Сьерра-Леоне",
    nameEn: "Sierra Leone",
    mask: "##-######",
    lengths: [8],
  },
  {
    iso: "TH",
    dial: "+66",
    name: "Таиланд",
    nameEn: "Thailand",
    mask: "##-###-###",
    lengths: [8, 9],
  },
  {
    iso: "TW",
    dial: "+886",
    name: "Тайвань",
    nameEn: "Taiwan",
    mask: "####-####",
    lengths: [8, 9],
  },
  {
    iso: "TZ",
    dial: "+255",
    name: "Танзания",
    nameEn: "Tanzania, United Republic of Tanzania",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "TC",
    dial: "+1",
    name: "Тёркс и Кайкос",
    nameEn: "Turks and Caicos Islands",
    mask: "(249) ###-###",
    lengths: [6],
  },
  {
    iso: "TG",
    dial: "+228",
    name: "Того",
    nameEn: "Togo",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "TK",
    dial: "+690",
    name: "Токелау",
    nameEn: "Tokelau",
    mask: "####",
    lengths: [4],
  },
  {
    iso: "TO",
    dial: "+676",
    name: "Тонга",
    nameEn: "Tonga",
    mask: "#####",
    lengths: [5],
  },
  {
    iso: "TT",
    dial: "+1",
    name: "Тринидад и Тобаго",
    nameEn: "Trinidad and Tobago",
    mask: "(868) ###-####",
    lengths: [7],
  },
  {
    iso: "TV",
    dial: "+688",
    name: "Тувалу",
    nameEn: "Tuvalu",
    mask: "2####",
    lengths: [4],
  },
  {
    iso: "TN",
    dial: "+216",
    name: "Тунис",
    nameEn: "Tunisia",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "UG",
    dial: "+256",
    name: "Уганда",
    nameEn: "Uganda",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "WF",
    dial: "+681",
    name: "Уоллис и Футуна",
    nameEn: "Wallis and Futuna",
    mask: "##-####",
    lengths: [6],
  },
  {
    iso: "UY",
    dial: "+598",
    name: "Уругвай",
    nameEn: "Uruguay",
    mask: "#-###-##-##",
    lengths: [8],
  },
  {
    iso: "FO",
    dial: "+298",
    name: "Фарерские о-ва",
    nameEn: "Faroe Islands",
    mask: "## ## ##",
    lengths: [6],
  },
  {
    iso: "FM",
    dial: "+691",
    name: "Федеративные Штаты Микронезии",
    nameEn: "Micronesia, Federated States of Micronesia",
    mask: "###-####",
    lengths: [7],
  },
  {
    iso: "FJ",
    dial: "+679",
    name: "Фиджи",
    nameEn: "Fiji",
    mask: "##-#####",
    lengths: [7],
  },
  {
    iso: "PH",
    dial: "+63",
    name: "Филиппины",
    nameEn: "Philippines",
    mask: "(###) ###-####",
    lengths: [10],
  },
  {
    iso: "FI",
    dial: "+358",
    name: "Финляндия",
    nameEn: "Finland",
    mask: "## ### ####",
    lengths: [9],
  },
  {
    iso: "FK",
    dial: "+500",
    name: "Фолклендские о-ва",
    nameEn: "Falkland Islands (Malvinas)",
    mask: "#####",
    lengths: [5],
  },
  {
    iso: "FR",
    dial: "+33",
    name: "Франция",
    nameEn: "France",
    mask: "# ## ## ## ##",
    lengths: [9],
  },
  {
    iso: "GF",
    dial: "+594",
    name: "Французская Гвиана",
    nameEn: "French Guiana",
    mask: "### ## ## ##",
    lengths: [9],
  },
  {
    iso: "PF",
    dial: "+689",
    name: "Французская Полинезия",
    nameEn: "French Polynesia",
    mask: "## ## ## ##",
    lengths: [8],
  },
  {
    iso: "HR",
    dial: "+385",
    name: "Хорватия",
    nameEn: "Croatia",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "CF",
    dial: "+236",
    name: "Центрально-Африканская Республика",
    nameEn: "Central African Republic",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "TD",
    dial: "+235",
    name: "Чад",
    nameEn: "Chad",
    mask: "##-##-##-##",
    lengths: [8],
  },
  {
    iso: "ME",
    dial: "+382",
    name: "Черногория",
    nameEn: "Montenegro",
    mask: "##-###-###",
    lengths: [8],
  },
  {
    iso: "CZ",
    dial: "+420",
    name: "Чехия",
    nameEn: "Czech Republic",
    mask: "(###) ###-###",
    lengths: [9],
  },
  {
    iso: "CL",
    dial: "+56",
    name: "Чили",
    nameEn: "Chile",
    mask: "#-####-####",
    lengths: [9],
  },
  {
    iso: "CH",
    dial: "+41",
    name: "Швейцария",
    nameEn: "Switzerland",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "SE",
    dial: "+46",
    name: "Швеция",
    nameEn: "Sweden",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "SJ",
    dial: "+47",
    name: "Шпицберген и Ян-Майен",
    nameEn: "Svalbard and Jan Mayen",
    mask: "(###) ##-###",
    lengths: [8],
  },
  {
    iso: "LK",
    dial: "+94",
    name: "Шри-Ланка",
    nameEn: "Sri Lanka",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "EC",
    dial: "+593",
    name: "Эквадор",
    nameEn: "Ecuador",
    mask: "#-###-####",
    lengths: [8, 9],
  },
  {
    iso: "GQ",
    dial: "+240",
    name: "Экваториальная Гвинея",
    nameEn: "Equatorial Guinea",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "ER",
    dial: "+291",
    name: "Эритрея",
    nameEn: "Eritrea",
    mask: "#-###-###",
    lengths: [7],
  },
  {
    iso: "SZ",
    dial: "+268",
    name: "Эсватини",
    nameEn: "Eswatini",
    mask: "##-##-####",
    lengths: [8],
  },
  {
    iso: "EE",
    dial: "+372",
    name: "Эстония",
    nameEn: "Estonia",
    mask: "###-####",
    lengths: [7, 8],
  },
  {
    iso: "ET",
    dial: "+251",
    name: "Эфиопия",
    nameEn: "Ethiopia",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "GS",
    dial: "+500",
    name: "Южная Георгия и Южные Сандвичевы о-ва",
    nameEn: "South Georgia and the South Sandwich Islands",
    mask: "#####",
    lengths: [5],
  },
  {
    iso: "ZA",
    dial: "+27",
    name: "Южно-Африканская Республика",
    nameEn: "South Africa",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "SS",
    dial: "+211",
    name: "Южный Судан",
    nameEn: "South Sudan",
    mask: "##-###-####",
    lengths: [9],
  },
  {
    iso: "JM",
    dial: "+1",
    name: "Ямайка",
    nameEn: "Jamaica",
    mask: "(876) ###-####",
    lengths: [7],
  },
  {
    iso: "JP",
    dial: "+81",
    name: "Япония",
    nameEn: "Japan",
    mask: "(###) ###-###",
    lengths: [9, 10],
  },
];
