/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClientPicker: typeof import('./components/ClientPicker.vue')['default']
    CreateClientDialog: typeof import('./components/CreateClientDialog.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    HeroSummary: typeof import('./components/HeroSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpgradePrompt: typeof import('./components/UpgradePrompt.vue')['default']
  }
}
