/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressPicker: typeof import('./components/AddressPicker.vue')['default']
    CashBoxEditDialog: typeof import('./components/CashBoxEditDialog.vue')['default']
    CashBoxLimitBlock: typeof import('./components/CashBoxLimitBlock.vue')['default']
    CashflowJournal: typeof import('./components/CashflowJournal.vue')['default']
    ChatPanel: typeof import('./components/ChatPanel.vue')['default']
    ClientPicker: typeof import('./components/ClientPicker.vue')['default']
    CoInvestorCashier: typeof import('./components/CoInvestorCashier.vue')['default']
    CoInvestorCreateDialog: typeof import('./components/CoInvestorCreateDialog.vue')['default']
    CoInvestorEditDialog: typeof import('./components/CoInvestorEditDialog.vue')['default']
    CoInvestorRemoveDialog: typeof import('./components/CoInvestorRemoveDialog.vue')['default']
    ComboBox: typeof import('./components/ComboBox.vue')['default']
    CreateClientDialog: typeof import('./components/CreateClientDialog.vue')['default']
    DealDraftFloater: typeof import('./components/DealDraftFloater.vue')['default']
    DealsSidebar: typeof import('./components/DealsSidebar.vue')['default']
    DebtorDetailModal: typeof import('./components/DebtorDetailModal.vue')['default']
    ExactValue: typeof import('./components/ExactValue.vue')['default']
    FolderCreateDialog: typeof import('./components/FolderCreateDialog.vue')['default']
    FormModal: typeof import('./components/FormModal.vue')['default']
    GlobalSearchDialog: typeof import('./components/GlobalSearchDialog.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    HelpBlock: typeof import('./components/help/HelpBlock.vue')['default']
    HelpNav: typeof import('./components/help/HelpNav.vue')['default']
    HelpRichText: typeof import('./components/help/HelpRichText.vue')['default']
    HeroSummary: typeof import('./components/HeroSummary.vue')['default']
    MetricDetailDialog: typeof import('./components/MetricDetailDialog.vue')['default']
    ProfitFormula: typeof import('./components/ProfitFormula.vue')['default']
    PromiseDialog: typeof import('./components/PromiseDialog.vue')['default']
    QuickActionsDialog: typeof import('./components/QuickActionsDialog.vue')['default']
    ReportsDealsTable: typeof import('./components/reports/ReportsDealsTable.vue')['default']
    ReportsDynamics: typeof import('./components/reports/ReportsDynamics.vue')['default']
    ReportsEfficiency: typeof import('./components/reports/ReportsEfficiency.vue')['default']
    ReportsMoneyNow: typeof import('./components/reports/ReportsMoneyNow.vue')['default']
    ReportsRisks: typeof import('./components/reports/ReportsRisks.vue')['default']
    ReportsTab: typeof import('./components/reports/ReportsTab.vue')['default']
    RolesManager: typeof import('./components/RolesManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteSheetFormDialog: typeof import('./components/RouteSheetFormDialog.vue')['default']
    RouteSheetsPanel: typeof import('./components/suppliers/RouteSheetsPanel.vue')['default']
    SubscriptionStatusBanner: typeof import('./components/SubscriptionStatusBanner.vue')['default']
    SupplierActivityPanel: typeof import('./components/suppliers/SupplierActivityPanel.vue')['default']
    SupplierDetail: typeof import('./components/SupplierDetail.vue')['default']
    SupplierFormDialog: typeof import('./components/SupplierFormDialog.vue')['default']
    SupplierMapDialog: typeof import('./components/SupplierMapDialog.vue')['default']
    SupplierPayoutDialog: typeof import('./components/SupplierPayoutDialog.vue')['default']
    SupplierRequestFormDialog: typeof import('./components/SupplierRequestFormDialog.vue')['default']
    SupplierRequestsPanel: typeof import('./components/suppliers/SupplierRequestsPanel.vue')['default']
    SupplierSelect: typeof import('./components/SupplierSelect.vue')['default']
    SuppliersListPanel: typeof import('./components/suppliers/SuppliersListPanel.vue')['default']
    UpgradePrompt: typeof import('./components/UpgradePrompt.vue')['default']
  }
}
