/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/accounting/': RouteRecordInfo<'/accounting/', '/accounting', Record<never, never>, Record<never, never>>,
    '/accounting/accounts/[id]': RouteRecordInfo<'/accounting/accounts/[id]', '/accounting/accounts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/accounting/audit': RouteRecordInfo<'/accounting/audit', '/accounting/audit', Record<never, never>, Record<never, never>>,
    '/accounting/balance': RouteRecordInfo<'/accounting/balance', '/accounting/balance', Record<never, never>, Record<never, never>>,
    '/accounting/history': RouteRecordInfo<'/accounting/history', '/accounting/history', Record<never, never>, Record<never, never>>,
    '/accounting/points/': RouteRecordInfo<'/accounting/points/', '/accounting/points', Record<never, never>, Record<never, never>>,
    '/accounting/points/[id]': RouteRecordInfo<'/accounting/points/[id]', '/accounting/points/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/accounting/reports': RouteRecordInfo<'/accounting/reports', '/accounting/reports', Record<never, never>, Record<never, never>>,
    '/accounting/temporary': RouteRecordInfo<'/accounting/temporary', '/accounting/temporary', Record<never, never>, Record<never, never>>,
    '/activity': RouteRecordInfo<'/activity', '/activity', Record<never, never>, Record<never, never>>,
    '/analytics': RouteRecordInfo<'/analytics', '/analytics', Record<never, never>, Record<never, never>>,
    '/backups': RouteRecordInfo<'/backups', '/backups', Record<never, never>, Record<never, never>>,
    '/broadcasts': RouteRecordInfo<'/broadcasts', '/broadcasts', Record<never, never>, Record<never, never>>,
    '/calculator': RouteRecordInfo<'/calculator', '/calculator', Record<never, never>, Record<never, never>>,
    '/cashboxes/': RouteRecordInfo<'/cashboxes/', '/cashboxes', Record<never, never>, Record<never, never>>,
    '/cashboxes/[id]': RouteRecordInfo<'/cashboxes/[id]', '/cashboxes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/clients': RouteRecordInfo<'/clients', '/clients', Record<never, never>, Record<never, never>, '/clients/' | '/clients/[id]'>,
    '/clients/': RouteRecordInfo<'/clients/', '/clients', Record<never, never>, Record<never, never>>,
    '/clients/[id]': RouteRecordInfo<'/clients/[id]', '/clients/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/co-investors': RouteRecordInfo<'/co-investors', '/co-investors', Record<never, never>, Record<never, never>, '/co-investors/' | '/co-investors/[id]' | '/co-investors/person/[id]'>,
    '/co-investors/': RouteRecordInfo<'/co-investors/', '/co-investors', Record<never, never>, Record<never, never>>,
    '/co-investors/[id]': RouteRecordInfo<'/co-investors/[id]', '/co-investors/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/co-investors/person/[id]': RouteRecordInfo<'/co-investors/person/[id]', '/co-investors/person/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/collections/': RouteRecordInfo<'/collections/', '/collections', Record<never, never>, Record<never, never>>,
    '/collections/[id]': RouteRecordInfo<'/collections/[id]', '/collections/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/contract-builder': RouteRecordInfo<'/contract-builder', '/contract-builder', Record<never, never>, Record<never, never>>,
    '/create-deal': RouteRecordInfo<'/create-deal', '/create-deal', Record<never, never>, Record<never, never>>,
    '/create-product': RouteRecordInfo<'/create-product', '/create-product', Record<never, never>, Record<never, never>>,
    '/deals': RouteRecordInfo<'/deals', '/deals', Record<never, never>, Record<never, never>, '/deals/' | '/deals/[id]'>,
    '/deals/': RouteRecordInfo<'/deals/', '/deals', Record<never, never>, Record<never, never>>,
    '/deals/[id]': RouteRecordInfo<'/deals/[id]', '/deals/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/debtors': RouteRecordInfo<'/debtors', '/debtors', Record<never, never>, Record<never, never>>,
    '/forgot-password': RouteRecordInfo<'/forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/guarantors': RouteRecordInfo<'/guarantors', '/guarantors', Record<never, never>, Record<never, never>>,
    '/help': RouteRecordInfo<'/help', '/help', Record<never, never>, Record<never, never>>,
    '/import/': RouteRecordInfo<'/import/', '/import', Record<never, never>, Record<never, never>>,
    '/import/drafts/[id]': RouteRecordInfo<'/import/drafts/[id]', '/import/drafts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/investor/[token]': RouteRecordInfo<'/investor/[token]', '/investor/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/me': RouteRecordInfo<'/me', '/me', Record<never, never>, Record<never, never>>,
    '/messages': RouteRecordInfo<'/messages', '/messages', Record<never, never>, Record<never, never>>,
    '/payments': RouteRecordInfo<'/payments', '/payments', Record<never, never>, Record<never, never>>,
    '/point/': RouteRecordInfo<'/point/', '/point', Record<never, never>, Record<never, never>>,
    '/point/cash': RouteRecordInfo<'/point/cash', '/point/cash', Record<never, never>, Record<never, never>>,
    '/point/handover': RouteRecordInfo<'/point/handover', '/point/handover', Record<never, never>, Record<never, never>>,
    '/point/history': RouteRecordInfo<'/point/history', '/point/history', Record<never, never>, Record<never, never>>,
    '/products': RouteRecordInfo<'/products', '/products', Record<never, never>, Record<never, never>, '/products/' | '/products/[id]'>,
    '/products/': RouteRecordInfo<'/products/', '/products', Record<never, never>, Record<never, never>>,
    '/products/[id]': RouteRecordInfo<'/products/[id]', '/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/receipt-template': RouteRecordInfo<'/receipt-template', '/receipt-template', Record<never, never>, Record<never, never>>,
    '/registry': RouteRecordInfo<'/registry', '/registry', Record<never, never>, Record<never, never>>,
    '/requests': RouteRecordInfo<'/requests', '/requests', Record<never, never>, Record<never, never>>,
    '/reset-password': RouteRecordInfo<'/reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/staff': RouteRecordInfo<'/staff', '/staff', Record<never, never>, Record<never, never>, '/staff/' | '/staff/[id]'>,
    '/staff/': RouteRecordInfo<'/staff/', '/staff', Record<never, never>, Record<never, never>>,
    '/staff/[id]': RouteRecordInfo<'/staff/[id]', '/staff/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/suppliers': RouteRecordInfo<'/suppliers', '/suppliers', Record<never, never>, Record<never, never>, '/suppliers/' | '/suppliers/[id]' | '/suppliers/route-sheets/[id]'>,
    '/suppliers/': RouteRecordInfo<'/suppliers/', '/suppliers', Record<never, never>, Record<never, never>>,
    '/suppliers/[id]': RouteRecordInfo<'/suppliers/[id]', '/suppliers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/suppliers/route-sheets/[id]': RouteRecordInfo<'/suppliers/route-sheets/[id]', '/suppliers/route-sheets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/zakat': RouteRecordInfo<'/zakat', '/zakat', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/accounting/index.vue': {
      routes: '/accounting/'
      views: never
    }
    'src/pages/accounting/accounts/[id].vue': {
      routes: '/accounting/accounts/[id]'
      views: never
    }
    'src/pages/accounting/audit.vue': {
      routes: '/accounting/audit'
      views: never
    }
    'src/pages/accounting/balance.vue': {
      routes: '/accounting/balance'
      views: never
    }
    'src/pages/accounting/history.vue': {
      routes: '/accounting/history'
      views: never
    }
    'src/pages/accounting/points/index.vue': {
      routes: '/accounting/points/'
      views: never
    }
    'src/pages/accounting/points/[id].vue': {
      routes: '/accounting/points/[id]'
      views: never
    }
    'src/pages/accounting/reports.vue': {
      routes: '/accounting/reports'
      views: never
    }
    'src/pages/accounting/temporary.vue': {
      routes: '/accounting/temporary'
      views: never
    }
    'src/pages/activity.vue': {
      routes: '/activity'
      views: never
    }
    'src/pages/analytics.vue': {
      routes: '/analytics'
      views: never
    }
    'src/pages/backups.vue': {
      routes: '/backups'
      views: never
    }
    'src/pages/broadcasts.vue': {
      routes: '/broadcasts'
      views: never
    }
    'src/pages/calculator.vue': {
      routes: '/calculator'
      views: never
    }
    'src/pages/cashboxes/index.vue': {
      routes: '/cashboxes/'
      views: never
    }
    'src/pages/cashboxes/[id].vue': {
      routes: '/cashboxes/[id]'
      views: never
    }
    'src/pages/clients.vue': {
      routes: '/clients' | '/clients/' | '/clients/[id]'
      views: 'default'
    }
    'src/pages/clients/index.vue': {
      routes: '/clients/'
      views: never
    }
    'src/pages/clients/[id].vue': {
      routes: '/clients/[id]'
      views: never
    }
    'src/pages/co-investors.vue': {
      routes: '/co-investors' | '/co-investors/' | '/co-investors/[id]' | '/co-investors/person/[id]' | '/co-investors/person'
      views: 'default'
    }
    'src/pages/co-investors/index.vue': {
      routes: '/co-investors/'
      views: never
    }
    'src/pages/co-investors/[id].vue': {
      routes: '/co-investors/[id]'
      views: never
    }
    'src/pages/co-investors/person/[id].vue': {
      routes: '/co-investors/person/[id]'
      views: never
    }
    'src/pages/collections/index.vue': {
      routes: '/collections/'
      views: never
    }
    'src/pages/collections/[id].vue': {
      routes: '/collections/[id]'
      views: never
    }
    'src/pages/contract-builder.vue': {
      routes: '/contract-builder'
      views: never
    }
    'src/pages/create-deal.vue': {
      routes: '/create-deal'
      views: never
    }
    'src/pages/create-product.vue': {
      routes: '/create-product'
      views: never
    }
    'src/pages/deals.vue': {
      routes: '/deals' | '/deals/' | '/deals/[id]'
      views: 'default'
    }
    'src/pages/deals/index.vue': {
      routes: '/deals/'
      views: never
    }
    'src/pages/deals/[id].vue': {
      routes: '/deals/[id]'
      views: never
    }
    'src/pages/debtors.vue': {
      routes: '/debtors'
      views: never
    }
    'src/pages/forgot-password.vue': {
      routes: '/forgot-password'
      views: never
    }
    'src/pages/guarantors.vue': {
      routes: '/guarantors'
      views: never
    }
    'src/pages/help.vue': {
      routes: '/help'
      views: never
    }
    'src/pages/import/index.vue': {
      routes: '/import/'
      views: never
    }
    'src/pages/import/drafts/[id].vue': {
      routes: '/import/drafts/[id]'
      views: never
    }
    'src/pages/investor/[token].vue': {
      routes: '/investor/[token]'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/me.vue': {
      routes: '/me'
      views: never
    }
    'src/pages/messages.vue': {
      routes: '/messages'
      views: never
    }
    'src/pages/payments.vue': {
      routes: '/payments'
      views: never
    }
    'src/pages/point/index.vue': {
      routes: '/point/'
      views: never
    }
    'src/pages/point/cash.vue': {
      routes: '/point/cash'
      views: never
    }
    'src/pages/point/handover.vue': {
      routes: '/point/handover'
      views: never
    }
    'src/pages/point/history.vue': {
      routes: '/point/history'
      views: never
    }
    'src/pages/products.vue': {
      routes: '/products' | '/products/' | '/products/[id]'
      views: 'default'
    }
    'src/pages/products/index.vue': {
      routes: '/products/'
      views: never
    }
    'src/pages/products/[id].vue': {
      routes: '/products/[id]'
      views: never
    }
    'src/pages/receipt-template.vue': {
      routes: '/receipt-template'
      views: never
    }
    'src/pages/registry.vue': {
      routes: '/registry'
      views: never
    }
    'src/pages/requests.vue': {
      routes: '/requests'
      views: never
    }
    'src/pages/reset-password.vue': {
      routes: '/reset-password'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/staff.vue': {
      routes: '/staff' | '/staff/' | '/staff/[id]'
      views: 'default'
    }
    'src/pages/staff/index.vue': {
      routes: '/staff/'
      views: never
    }
    'src/pages/staff/[id].vue': {
      routes: '/staff/[id]'
      views: never
    }
    'src/pages/suppliers.vue': {
      routes: '/suppliers' | '/suppliers/' | '/suppliers/[id]' | '/suppliers/route-sheets/[id]' | '/suppliers/route-sheets'
      views: 'default'
    }
    'src/pages/suppliers/index.vue': {
      routes: '/suppliers/'
      views: never
    }
    'src/pages/suppliers/[id].vue': {
      routes: '/suppliers/[id]'
      views: never
    }
    'src/pages/suppliers/route-sheets/[id].vue': {
      routes: '/suppliers/route-sheets/[id]'
      views: never
    }
    'src/pages/zakat.vue': {
      routes: '/zakat'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
