/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activity': RouteRecordInfo<'/activity', '/activity', Record<never, never>, Record<never, never>>,
    '/analytics': RouteRecordInfo<'/analytics', '/analytics', Record<never, never>, Record<never, never>>,
    '/calculator': RouteRecordInfo<'/calculator', '/calculator', Record<never, never>, Record<never, never>>,
    '/clients': RouteRecordInfo<'/clients', '/clients', Record<never, never>, Record<never, never>, '/clients/' | '/clients/[id]'>,
    '/clients/': RouteRecordInfo<'/clients/', '/clients', Record<never, never>, Record<never, never>>,
    '/clients/[id]': RouteRecordInfo<'/clients/[id]', '/clients/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/co-investors': RouteRecordInfo<'/co-investors', '/co-investors', Record<never, never>, Record<never, never>>,
    '/create-deal': RouteRecordInfo<'/create-deal', '/create-deal', Record<never, never>, Record<never, never>>,
    '/create-product': RouteRecordInfo<'/create-product', '/create-product', Record<never, never>, Record<never, never>>,
    '/deals': RouteRecordInfo<'/deals', '/deals', Record<never, never>, Record<never, never>, '/deals/' | '/deals/[id]'>,
    '/deals/': RouteRecordInfo<'/deals/', '/deals', Record<never, never>, Record<never, never>>,
    '/deals/[id]': RouteRecordInfo<'/deals/[id]', '/deals/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/finance': RouteRecordInfo<'/finance', '/finance', Record<never, never>, Record<never, never>>,
    '/import': RouteRecordInfo<'/import', '/import', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/notifications': RouteRecordInfo<'/notifications', '/notifications', Record<never, never>, Record<never, never>>,
    '/payments': RouteRecordInfo<'/payments', '/payments', Record<never, never>, Record<never, never>>,
    '/products': RouteRecordInfo<'/products', '/products', Record<never, never>, Record<never, never>, '/products/' | '/products/[id]'>,
    '/products/': RouteRecordInfo<'/products/', '/products', Record<never, never>, Record<never, never>>,
    '/products/[id]': RouteRecordInfo<'/products/[id]', '/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/registry': RouteRecordInfo<'/registry', '/registry', Record<never, never>, Record<never, never>>,
    '/requests': RouteRecordInfo<'/requests', '/requests', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/staff': RouteRecordInfo<'/staff', '/staff', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/activity.vue': {
      routes: '/activity'
      views: never
    }
    'src/pages/analytics.vue': {
      routes: '/analytics'
      views: never
    }
    'src/pages/calculator.vue': {
      routes: '/calculator'
      views: never
    }
    'src/pages/clients.vue': {
      routes: '/clients' | '/clients/' | '/clients/[id]'
      views: 'default'
    }
    'src/pages/clients/index.vue': {
      routes: '/clients/'
      views: never
    }
    'src/pages/clients/[id].vue': {
      routes: '/clients/[id]'
      views: never
    }
    'src/pages/co-investors.vue': {
      routes: '/co-investors'
      views: never
    }
    'src/pages/create-deal.vue': {
      routes: '/create-deal'
      views: never
    }
    'src/pages/create-product.vue': {
      routes: '/create-product'
      views: never
    }
    'src/pages/deals.vue': {
      routes: '/deals' | '/deals/' | '/deals/[id]'
      views: 'default'
    }
    'src/pages/deals/index.vue': {
      routes: '/deals/'
      views: never
    }
    'src/pages/deals/[id].vue': {
      routes: '/deals/[id]'
      views: never
    }
    'src/pages/finance.vue': {
      routes: '/finance'
      views: never
    }
    'src/pages/import.vue': {
      routes: '/import'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/notifications.vue': {
      routes: '/notifications'
      views: never
    }
    'src/pages/payments.vue': {
      routes: '/payments'
      views: never
    }
    'src/pages/products.vue': {
      routes: '/products' | '/products/' | '/products/[id]'
      views: 'default'
    }
    'src/pages/products/index.vue': {
      routes: '/products/'
      views: never
    }
    'src/pages/products/[id].vue': {
      routes: '/products/[id]'
      views: never
    }
    'src/pages/registry.vue': {
      routes: '/registry'
      views: never
    }
    'src/pages/requests.vue': {
      routes: '/requests'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/staff.vue': {
      routes: '/staff'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
